// This file is auto-generated by Convex. Do not modify.
// Run `npx convex dev` to regenerate these types.

import type { FunctionReference } from "convex/server";

/**
 * A reference to a specific function within your Convex app.
 *
 * Use `api` to get a reference to a function:
 *
 * ```ts
 * import { api } from "../convex/_generated";
 * import { useQuery } from "convex/react";
 *
 * const functionReference = api.myFolder.myFunction;
 * const data = useQuery(functionReference);
 * ```
 *
 * To reference a function defined in:
 * - `convex/myFolder/myFile.ts`, use `api.myFolder.myFile.myFunction`
 * - `convex/myFile.ts`, use `api.myFile.myFunction`
 *
 * This file is a stub - run `npx convex dev` to generate the real types.
 */
export const api = {} as any;
