// This file is auto-generated by Convex. Do not modify.
// Run `npx convex dev` to regenerate these types.

import type { AnyDataModel } from "convex/server";

/**
 * The type of data in your Convex database.
 *
 * This file is a stub - run `npx convex dev` to generate the real types.
 */
export type DataModel = AnyDataModel;

/**
 * A type referencing a document in the database.
 */
export type Doc<Table extends DataModelTableName> = any;

/**
 * A type representing a document ID.
 */
export type DocumentByName<Table extends DataModelTableName> = any;

/**
 * The names of tables in your data model.
 */
export type DataModelTableName = any;
