// This file is auto-generated by Convex. Do not modify.
// Run `npx convex dev` to regenerate these types.

import type { DataModel } from "./dataModel";

/**
 * Define a mutation in a Convex app.
 *
 * This is a stub - run `npx convex dev` to generate the real types.
 */
export const mutation: any = {} as any;

/**
 * Define a query in a Convex app.
 *
 * This is a stub - run `npx convex dev` to generate the real types.
 */
export const query: any = {} as any;

/**
 * Define an action in a Convex app.
 *
 * This is a stub - run `npx convex dev` to generate the real types.
 */
export const action: any = {} as any;
